Feat/emoji picker
moonshotcollective/drecruit pull request #38
Opened 2021-11-05 07:40 UTC by Dhaiwat10

Closes #31 

I've targeted the PR at the staging branch. Let me know if this should be main instead.

2021-11-05 07:49 UTC, Dhaiwat10 commented
I think there are three extra commits that are popping up because I created my new branch off of the `main` branch..sorry about that. I think we'll have to rebase/squash

2021-11-09 03:48 UTC, Cali93 requested changes

2021-11-09 03:48 UTC, Cali93 commented on packages/react-app/pages/profile/edit-profile.js
> +const emojis = ["🚀", "🙏", "👻", "🤌", "👀"];
Can you use this array of emoji instead ? https://gist.github.com/anthonydelgado/528d1fab9242067348c0ac25f873d7f0

2021-11-09 05:27 UTC, Dhaiwat10 commented
Done

2021-11-09 17:00 UTC, QEDK commented
@Dhaiwat10 can you address the conflicts, ty

2021-11-09 17:46 UTC, Dhaiwat10 commented
@QEDK done.

2021-11-09 19:13 UTC, Cali93 approved these changes

2021-11-09 19:13 UTC, merged